version: "3.8"
services:
  db-url:
    image: redis:alpine
  db-id:
    image: redis:alpine
  backend:
    build: backend
    env_file:
      - ./docker/vars/backend.env
    depends_on:
      - db-url
      - db-id
  proxy_frontend:
    build: proxy_frontend
    ports:
      - 80:3000
    depends_on:
      - backend
  qrcode:
    build: qrcode